name: Build Nockchain Node

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROTOC: protoc

    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies & Protobuf
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang libssl-dev pkg-config protobuf-compiler libprotobuf-dev

      - name: Verify Protoc
        run: protoc --version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Node Binary
        run: cargo build --release

      - name: Upload Node Binary
        uses: actions/upload-artifact@v4
        with:
          name: nockchain-node-binary
          path: target/release/nockchain
